Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2023-08, with the labels that each got.

#118 [ALS-4797] Add Configurable Google Analytics.
  pic-sure-hpds-ui/src/main/resources/settings.json
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
Labels: enhancement

#119 [ALS-4464] Selection search box supports infinite scroll with data from the backend or large datasets
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/modal.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: enhancement

#120 [ALS-4464] Bug fixes and performance improvements
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel.hbs
Labels: ignore-for-release

#121 [ALS-4932] Rename Finalize dataset modal
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/outputPanel.js
Labels: bug

#122 [ALS-4933] Decouple variant explorer and output panel
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantTable.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: bug, enhancement

#125 [ALS-4947] Update queryBuilder to use new anyRecordOfMulti field
  pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
Labels: enhancement
