Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2023-09, with the labels that each got.

#130 label checker
  .github/workflows/github-actions-deploy-snapshots.yml
  .github/workflows/github-actions-test.yml
  .github/workflows/label-checker.yml
Labels: ignore-for-release

#127 [ALS-4990] Fix bug where options were disabled incorrectly
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
Labels: bug

#131 I moved fast and broke things
  .github/workflows/github-actions-deploy-snapshots.yml
  .github/workflows/github-actions-test.yml
Labels: ignore-for-release

#134 [ALS-0000] Support queries with multiple gene clauses
  pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
Labels: bug

#142 [ALS-5051] Upgrade DataTables to latest web jar version
  pic-sure-hpds-ui-libs/pom.xml
  pic-sure-hpds-ui/src/main/webapp/picsureui/main.js
Labels: dependencies, ignore-for-release

#139 [ALS-5072] Let's not subtract 2 from the variant count
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
Labels: bug

#141 [ALS-5073] Fix Variant Explorer data tables error
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
Labels: bug

#136 [ALS-4918] New search interface; enable genomic filter modal
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/mainLayout.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/selected-genomic-filters.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/selected-genomic-filters.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/variant-data.json
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: enhancement

#149 [ALS-5107] Add configurable banner section
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/bannerConfig.js
Labels: enhancement

#150 [ALS-5107] Add configurable banner section (#149)
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/bannerConfig.js
Labels: enhancement
