Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2023-11, with the labels that each got.

#170 [ALS-4773] [ALS-5244] Refactoring the data-view modal to work on other pages and allow copying
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-manage.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-save.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-view.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/utilities.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/dataset/utilities.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: enhancement

#172 [ALS-5334] Make freq description configurable
  pic-sure-hpds-ui-extension-archetype/src/main/resources/archetype-resources/src/main/webapp/picsureui/overrides/genomic-filter-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/genomic-filter-view.js
Labels: enhancement

#169 [ALS-5308] Fix protein_altering_variant
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/variant-data.json
Labels: bug

#175 [ALS-5323] Bugfix/add any record of multi count
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/package-data-view.js
Labels: bug

#171 [ALS-5244] Bugfix for range vs value logic on dataset string render utility
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-save.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/utilities.js
Labels: bug

#176 [ALS-5337] Fix select all
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
Labels: bug

#173 [ALS-5317] Create a tour: Baseline
  pic-sure-hpds-ui/src/main/resources/settings.json
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/mainLayout.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/pic-sure-dialog-view.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/session.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/searchResultSubCategoriesContainer.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/searchResultTabs.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/searchResults.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
  pic-sure-hpds-ui/src/main/webapp/picsureui/tour/tour-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/tour/tour.json
Labels: enhancement

#168 [ALS-5000] BDC: old version of log4j sitting in a repo
  pic-sure-hpds-ui-extension-archetype/pom.xml
  pic-sure-hpds-ui-libs/pom.xml
  pic-sure-hpds-ui/pom.xml
Labels: dependencies, ignore-for-release

#166 [ALS-5138] banner improvements
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/main.js
Labels: enhancement

#178 [ALS-5383] Fix bug where UI was stripping spaces from variables. (#177)
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.js
Labels: bug
