Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2023-10, with the labels that each got.

#148 [ALS-5042] Add google tag manager and cookie preferences popup
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/googleAnalytics.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/googleAnalytics.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/index.html
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: enhancement

#152 Merge Open Release into Release/0004
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
Labels: ignore-for-release

#154 Release 0004
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/googleAnalytics.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/googleAnalytics.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/googleAnalytics.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/index.html
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: ignore-for-release

#155 [ALS-0000] Prevent maxVariantCount being undefined
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
Labels: bug

#156 [ALS-4918] Style updates and interface changes
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/tree-select.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: ignore-for-release

#157 [ALS-5112] "Open PIC-SURE Explorer" takes the user to a blank page
  pic-sure-hpds-ui/src/main/webapp/picsureui/main.js
Labels: bug

#162 [ALS-5231] Add variant severity to merge function
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
Labels: bug

#161 [ALS-5216] Add a 401 check to genomic filter
  pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
Labels: bug

#163 [ALS-4918] Add border search
  pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Labels: ignore-for-release
