Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2024-02, with the labels that each got.

#182 [ALS-2668] Remove virtual host configuration files
  pic-sure-hpds-ui/Dockerfile
Labels: enhancement, ignore-for-release

#190 [ALS-5902] Update logout redirect URL in header.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/header.js
Labels: enhancement

#191 Add psama
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/roleFunctions.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/addManualStudy.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/addManualStudy.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/roleManagement.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/roleManagement.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/user/userDetails.js
Labels: enhancement

#192 Fix missing file
  pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/userDetails.js
Labels: ignore-for-release
