Repository hms-dbmi/pic-sure-core-frontend, pull requests merged in 2024-01, with the labels that each got.

#183 [ALS-5510] Update JUnit
  pic-sure-hpds-ui-extension-archetype/src/main/resources/archetype-resources/pom.xml
  pic-sure-hpds-ui/pom.xml
Labels: ignore-for-release

#184 [ALS-5567] Add dynamic login link to not_authorized template
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/login/login.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/login/not_authorized.hbs
Labels: enhancement

#185 [ALS-5100] Update consent text and make link configurable
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.hbs
  pic-sure-hpds-ui/src/main/webapp/picsureui/analytics/cookie-consent.js
Labels: enhancement

#187 [ALS-5580] Move close button color logic to router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
Labels: bug

#188 [ALS-5580] Fix banner
  pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
  pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
Labels: bug
